# theme options must NOT be provided via cli
# colors are supported only as #ffffff format, not three rgb values or string like "white"

[prompt]
# old: prompt-text
# must default to: none
text = "run: "

# old: prompt-padding
# must default to: 0
padding = 0

[results]
# old: num-results
# must default to: 0 (behave same as now - show everything that can be shown at a time)
count = 0

# old: result-spacing
# must default to: 25
spacing = 25

# old: horizontal
# must default to: vertical
mode = "vertical"

[text]
# old: prompt-text
# must default to: none
prompt = "run: "

# old: text-color
# must default to: white
color = "#c3c7c8"

# old: prompt_color
# must default to: white
prompt_color = "#f9dc5c"

# old: placeholder-color
# must default to: none
placeholder-color = "#ffffffa8"

# old: input-color
# must default to: white
input-color = "#00c1e4"

# old: default-result-color
# must default to: white
match_color = "#ffffff"

# old: selection-color
# must default to: yellow
selection_color = "#bd93f9"

# old: selection-match-color
# must default to: none
selection_match_color = "#00000000"

[font]
# old: font
# must default to: none
name = "CaskaydiaCove Nerd Font Mono"

# old: font-size
# must default to: 24
size = 24

# old: font-features
# must default to: none
features = ""

# old: font-variations
# must default to: none
variations = ""

# old: hint-font
# must default to: true
hint = true

[window]
# old: anchor
# must default to: center
anchor = "center"

# old: margin_top
# must default to: 0
margin_top = 0
# old: margin_bottom
# must default to: 0
margin_bottom = 0

# old: margin_left
# must default to: 0
margin_left = 0

# old: margin_right
# must default to: 0
margin_right = 0

# old: width
# must default to: 45%
width = "45%"

# old: height
# must default to: 60%
height = "60%"

# old: background-color
# must default to: black
background_color = "#000000bb"

# old: outline-width
# must default to: 1
outline_width = 1

# old: outline-color
# must default to: none
outline_color = "#ed254eff"

# old: border-width
# must default to: 2
border_width = 2

# old: border-color
# must default to: black
border_color = "#c74dedff"

# old: corner-radius
# must default to: 50
corner_radius = 50

# old: padding-top
# must default to: 35%
padding_top = "35%"

# old: padding-bottom
# must default to: 0
padding_bottom = 0

# old: padding-left
# must default to: 35%
padding_left = "35%"

# old: padding-right
# must default to: 0
padding_right = 0

# old: clip-to-padding
# must default to: true
clip_to_padding = true

# old: scale
# must default to: true
scale = true

[cursor]
# old: hide-cursor
# must default to: false
hide = false

[input]
# old: text-cursor
# must default to: false
cursor = false

# old: text-cursor-style
# must default to: bar
cursor_style = "bar"

# old: text-cursor-color
# must default to: white
cursor_color = "#ffffff"

# old: text-cursor-background
# must default to: black
cursor_background = "#000000"

# old: text-cursor-corner-radius
# must default to: 0
cursor_corner_radius = 0

# old: text-cursor-thickness
# must default to: 2
cursor_thickness = 2

# old: hide-input
# must default to: false
hide = false

# old: hidden-character
# must default to: *
hidden_character = "*"
